### ISSUE TITLE
`vds-radio-check` rendering the dot off-center by default

### ISSUE THREAD

**Issue by miketdonahue** [vidstack/vds-elements#1000]
Sorry for the nit-pick here folks, I am a little "nuts" as they would say, but I love what you all have done with the Player and I hope I am just helping out to make it incrementally more awesome.

### Current Behavior:

The class `vds-radio-check` on the `Player` currently has the `width` and `height` properties set to:

`var(--media-menu-radio-check-size, 9px);`

I realize that I can set the `--media-menu-radio-check-size` value to correct any sizing issues (which I have done), but I believe this means that by **default**, the "dot" is off-center due to the math, e.g. 9px is a pixel too small.

![Screenshot 2023-11-09 at 1 30 42 PM](https://github.com/vidstack/player/assets/8016033/236f7852-6b83-42c0-a50b-2af662638ef1)

### Expected Behavior:

By default, I would expect the CSS to "just work". I believe to get it to just work the fallback number for the `width` and `height` properties needs to be `10px`, not 9px.

### Steps To Reproduce:

Just take a look at the "Speed" settings in the Player.

![Screenshot 2023-11-09 at 1 30 28 PM](https://github.com/vidstack/player/assets/8016033/22615389-5345-4bf8-9f61-8f625ce16e40)

### Environment:

- Framework: React
- Meta Framework: Next.js
- Node: 18.17.0
- Device: Chrome
- Browser: Version 119.0.6045.105

**Comment by mihar-22** [comment]
Thanks for the report! Hm unless I'm missing something I can't repro this. The sizing by default seems to be correct and centered?
