### ISSUE TITLE
useMediaRemote is null

### ISSUE THREAD

**Issue by Julienblc** [vidstack/vds-elements#1076]
### Current Behavior:

I want to interact with the player, like play or pause a video with a button outside the player.
It's working using the player reference (useRef) but not using the useMediaRemote. The remote object is null.

### Expected Behavior:

Remote object should expose functions and not be null

### Steps To Reproduce:

[sandbox](https://codesandbox.io/p/sandbox/vidstack-video-forked-g68nnv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr541cg800063b6e3t0drsg6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr541cg800023b6e2n025x0u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr541cg800033b6eiw89ers2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr541cg800053b6eoyeqz5ec%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr541cg800023b6e2n025x0u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr541cg800013b6egk1yaytc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr542z5w003w3b6e2oa6tagm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr541cg800023b6e2n025x0u%2522%252C%2522activeTabId%2522%253A%2522clr542z5w003w3b6e2oa6tagm%2522%257D%252C%2522clr541cg800053b6eoyeqz5ec%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr541cg800043b6eg4tcona9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr541cg800053b6eoyeqz5ec%2522%252C%2522activeTabId%2522%253A%2522clr541cg800043b6eg4tcona9%2522%257D%252C%2522clr541cg800033b6eiw89ers2%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr541cg800033b6eiw89ers2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

You can check the logs

### Environment:

- "@vidstack/react": "1.9.8",
- "loader-utils": "3.2.1",
- "react": "18.2.0",
- "react-dom": "18.2.0",
- "react-scripts": "5.0.1"

**Comment by Julienblc** [comment]
Edit : 
Working when the `useMediaRemote()` hook is called inside the MediaPlayer like this : 

```ts
<MediaPlayer>
<MediaPlayer />
```

**Comment by Curetix** [comment]
That is how it is supposed to work. If the hook is called outside of the `MediaPlayer` component, you need to pass a ref to the player as argument, e.g.:

```tsx
const playerRef = useRef<MediaPlayerInstance>(null);
const remote = useMediaRemote(playerRef);
```

**Comment by Julienblc** [comment]
Ok it's working, thank you !
Just to understand, how the playerRef, which is a RefObject<MediaPlayerInstance> could fit with the useMediaRemote parameters types ?
<img width="938" alt="Capture d’écran 2024-01-08 à 21 02 10" src="https://github.com/vidstack/player/assets/7222986/cacc84ab-9cc7-498d-8d82-c2991706ebce">

**Comment by Curetix** [comment]
`useRef<MediaPlayerInstance>(null)` returns `React.RefObject<MediaPlayerInstance>`.

I assume that `MediaPlayerInstance` satisfies the `EventTarget` type, so it would be a valid type for the `target` argument of `useMediaRemote`.
