### ISSUE TITLE
Unlisted Vimeo-Videos won't play

### ISSUE THREAD

**Issue by bitbirddev** [vidstack/vds-elements#1100]
### Current Behavior:

Vidstack Player doesn't play Videos from Youtube that are marked as "unlisted". It is stuck with the loading animation

<img width="1776" alt="image" src="https://github.com/vidstack/player/assets/15128942/ac0bdb69-b528-455c-89d6-818bf2c21568">

### Expected Behavior:

Player should also play "unlisted" Videos

### Steps To Reproduce:

add the vidstack player and the official vimeo iframe embed to a page side by side

<img width="902" alt="SCR-20240123-piot" src="https://github.com/vidstack/player/assets/15128942/b73b6d77-ff04-4e80-97a4-637993102634">

```html
<media-player>
  <media-provider>
    <source src="https://player.vimeo.com/video/763694880?hash=e21fea6134"
        type="video/vimeo">
  </media-provider>
  <media-video-layout></media-video-layout>
  <media-audio-layout></media-audio-layout>
</media-player>

```

```html
<div style="padding:56.25% 0 0 0;position:relative;">
    <iframe src="https://player.vimeo.com/video/763694880?h=e21fea6134&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
            frameborder="0"
            allow="autoplay; fullscreen; picture-in-picture"
            style="position:absolute; top:0; left:0; width:100%; height:100%" 
            title="fit4future Kids - Spiele mit dem Reifen">
    </iframe>
</div>
```

### Anything Else?

seems like the player gets stuck when trying to load the embed-info (which is not available for unlisted videos)
<img width="755" alt="SCR-20240123-pfyn" src="https://github.com/vidstack/player/assets/15128942/71814873-f100-491d-ae7d-ac08f766d0bd">

the bug might be somewhere in here...

https://github.com/vidstack/player/blob/49bf0a71cd35ae7bfa8e9a058e345224b4693865/packages/vidstack/src/providers/vimeo/utils.ts#L14

https://github.com/vidstack/player/blob/49bf0a71cd35ae7bfa8e9a058e345224b4693865/packages/vidstack/src/providers/vimeo/provider.ts#L222

**Comment by qlaffont** [comment]
any update / progress on this issue ? @mihar-22  ?

**Comment by bitbirddev** [comment]
@mihar-22 feel free to test the issue with this video

```https://player.vimeo.com/video/763694880?h=e21fea6134```

its unlisted in vimeo but viewable on any domain.

**Comment by qlaffont** [comment]
> any update / progress on this issue ? @mihar-22 ?

:wave:

**Comment by mihar-22** [comment]
I've tried testing with test URL provided but it works for me?

**Comment by bitbirddev** [comment]
@mihar-22
[please take a look at this example on stackblitz.com](https://stackblitz.com/edit/web-platform-5f2qzy?file=index.html)

double checked the video id - its unlisted.

**Comment by bitbirddev** [comment]
@mihar-22 thanks for the bugfix! everything is working fine now!

**Comment by imadys** [comment]
Hello,
What about URLs contains two IDs ?
https://vimeo.com/${idOne}/${idTwo}
