### ISSUE TITLE
Youtube doesn't play on first click

### ISSUE THREAD

**Issue by wplit** [vidstack/vds-elements#1393]
The second part of my previous bug report is still happening in v1.12.8

When using Youtube provider, the video is paused immediately after pressing play the very first time, so a second press is needed.

Previous closed ticket that had mentioned it - https://github.com/vidstack/player/issues/1388

**Comment by 96imranahmed** [comment]
Not ideal, but I was able to workaround this by intercepting the `onPlayFail` handler and forcing a play event

```
          onPlayFail={(detail, nativeElement) => {
            if (nativeElement.isOriginTrusted) {
              playerRemote.play();
            }
          }}
```
