### ISSUE TITLE
How did the Webpack5 + ESBuild upgrades go?

### ISSUE THREAD

**Issue by tomByrer** [vidstack/vds-elements#198]
Was it tricky to upgrade?  I see you have to trick Storybook to work with ESBuild?
Is the new build system much faster?
TIA

**Comment by mihar-22** [comment]
Hey @tomByrer, it was relatively straight forward. Pretty much installed `@storybook/builder-webpack5` and then made the recommended changes in [`.storybook/main.js`](https://github.com/vidstack/vds-elements/blob/main/.storybook/main.js).

I wanted to test out trying `esbuild` and it seems to have sped things up (didn't do any proper performance tests). This is not the official way via Storybook "builders", they'll probably release a much better integration package soon (something like `@storybook/builder-esbuild`).

**Comment by tomByrer** [comment]
TY for the info!

Seems this plugin replaces Terser, though I think ESBuild can do much more?
https://storybook.js.org/addons/storybook-addon-turbo-build/
