### ISSUE TITLE
VolumeControl

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-elements#55]
## Tasks

- [x] Complete #35.
- [x] Complete #48.
- [x] Design, build and test the `VolumeControl` component.

## Notes

**CSS Parts**

Parts here are tricky and will need to be tested to find a suitable API.

- `volume-control`
- `volume-control-focused`
- `toggle-mute-control`.
- `control-*`, `mute-control-*` and `unmute-control-*`: Forward all `ToggleMuteControl` parts.
- `slider`: Forward all `Slider` parts.

## References

- https://github.com/vime-js/vime/tree/master/core/src/components/ui/controls/volume-control

**Comment by tomByrer** [comment]
It is OK if the UI clamps the volume levels 0 to 1.0, but please do not clamp (min/max) them in the core.  Sometimes I want to increase the volume past maximum.  (Often it is someone speaking too far from microphone, & they didn't compress the audio signal.  So I want my volume UI to go from 0.1-1.5 or so.)

Also, will you have the volume increase in a linear or logarithmic calculation?

**Comment by sampotts** [comment]
I'm not sure there's much value in adding support for anything higher than `1`. The spec for HTML5 has a maximum value of 1:

> A double value must fall between 0 and 1, where 0 is effectively muted and 1 is the loudest possible value.
http://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

Same for Vimeo:

> Set the volume of the player on a scale from 0 to 1.
https://github.com/vimeo/player.js/#setvolumevolume-number-promisenumber-rangeerrorerror

and YouTube uses `0` to `100`:

> Accepts an integer between 0 and 100.
https://developers.google.com/youtube/iframe_api_reference#setVolume

**Comment by tomByrer** [comment]
Ah ty.
I guess I'll have to boost somewhere else then, never mind :)
