### ISSUE TITLE
Get Video time

### ISSUE THREAD

**Issue by celymyst** [vidstack/vds-elements#711]
is there an easy way to get the current time as a variable?
i want to implement subtitle displaying to my test, and for that i need a way to update the text based on the current time

**Comment by mihar-22** [comment]
The best way would be the media store.

Vanilla JS

```js
const provider = document.querySelector('vds-video');

provider.store.currentTime.subscribe(time => {
  // time updates 
});
```

React

https://www.vidstack.io/docs/player/react/getting-started/foundation/#usemediacontext

**Comment by 5H4D0WILA** [comment]
i forgot that exists, thank you very much
